### ISSUE TITLE
Speech marks and slashes make YAML output funny for strings

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#163]
tl;dr: we need to do this on `error.message` in `_getErrorYaml`:

    .replace(/\\/g, "\\\\").replace(/"/g, "\\\"")

Because speech marks aren't being escaped, they're invalidating the YAML output. We need to escape them to keep things safe :)

Currently, the YAML output looks like this:

```
   message: "Expected "FAIL: Some failing test\\n    ---\\n    bla bla\\n    ---" to be "blah blah"."
   severity: fail
   data:
     got: "FAIL: Some failing test\n    ---\n    bla bla\n    ---"
     expect: "blah blah"
```

As you can see, the `message` property is invalid. The YAML should look like this:
```
   message: "Expected \"FAIL: Some failing test\\n    ---\\n    bla bla\\n    ---\" to be \"blah blah\"."
   severity: fail
   data:
     got: "FAIL: Some failing test\n    ---\n    bla bla\n    ---"
     expect: "blah blah"
```
