### ISSUE TITLE
Can `Any` be used with `toBe`?

### ISSUE THREAD

**Issue by brad-jones** [alsatian-test/alsatian#424]
Attempting to do something like: `Expect(result).toBe(Any(Object).thatMatches({foo: "bar"}));`

Is it possible?

I currently get the following output:
```
message: "Expected {\"baseUrl\":\".\"} to be Any Object and matches '{\"baseUrl\":\".\"}'."
   severity: fail
   data:
     got: {"baseUrl":"."}
     expect: {"_argumentStringifier":{},"_testers":[{},{}]}
```
